apiVersion: networking.k8s.io/v1beta
kind: Ingress
metadata:
  name:  {{ .Values.appname }}
  namespace: {{ .Values.appname }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: {{ .Values.appname }}
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: {{ .Values.appname }}
              servicePort: 80
